server:
  port: 9900
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2b8
    username: root
    password: root
  devtools:
    restart:
      enabled: false
  web:
    resources:
      static-locations: classpath:/static/**
mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  header: "Authorization" #token返回头部
  tokenPrefix: "Bearer " #token前缀
  secret: "zxczawdaw1q7418520" #密钥
  expireTime: 120 #token有效时间 (分钟) 建议一小时以上
files:
  upload:
    path: D:/Temp/files/
